POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "Testi Kakkonen Antero",
    "title": "Kakkonen bloggaus",
    "url": "testibloggaus v2",
    "likes": 2,
    "user": "661ff2134b5e11ecc0b15e8e"
}
