POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNhZXNqIiwiaWQiOiI2NjFmZjIxMzRiNWUxMWVjYzBiMTVlOGUiLCJpYXQiOjE3MTMzNzI4MzB9.q3wE8x2ibx0f5Mx8LWqL-3Cnz2DJLvLGmtHb7ee33jQ

{
    "author": "Testi Kolmonen Autentikointi",
    "title": "Kolmas bloggaus tokenilla",
    "url": "testibloggaus v3",
    "likes": 3
}
